name: Terraform Lint and Validate

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  TF_VERSION: "1.5.0"
  TFLINT_VERSION: "v0.44.1"

jobs:
  terraform-lint:
    name: Terraform Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: TFLint Init
        run: |
          cd bootstrap
          tflint --init
          cd ..

      - name: TFLint Check
        run: |
          echo "Checking bootstrap..."
          cd bootstrap
          tflint
          cd ..

          echo "Checking modules..."
          for dir in modules/*/; do
            if [ -f "$dir/main.tf" ]; then
              echo "Checking $dir"
              cd "$dir"
              tflint --init
              tflint
              cd ../..
            fi
          done

      - name: Terraform Validate
        run: |
          echo "Validating bootstrap..."
          cd bootstrap
          terraform init -backend=false
          terraform validate
          cd ..

          echo "Validating main..."
          terraform init -backend=false
          terraform validate
